#! /bin/sh

### BEGIN INIT INFO
# Provides:     crawlzilla
# Required-Start:   
# Required-Stop:    
# Default-Start:    2 3 4 5
# Default-Stop:     
# Short-Description:    crawlzilla services for master
#                       (start/stop tomcat, hadoop-namenode,jobnode,datanode,tasknode)
### END INIT INFO


