#!/bin/bash
# Program:
#   English Language file for nutchez
# Author:
#   Waue, Shunfa, Rock {waue, shunfa, rock}@nchc.org.tw
# Version:
#    1.0
# History:
#   2010/06/14  Rock    First release (1.0)

# [Variables Declaration] #
## Lang for common ##
user_error="Your identify is not nutchuser, plz change to \"nutchuser\" !!!"

## [Lang for dialog] ##
dia_back='= [NutchEz Management Interface] ~by NCHC ='
dia_choose="Plz choose: "
dia_exit="Exit"

## [Lang for prepare_check] ##
dia_pre_check_title_1="[nutch_nodes Files]"
dia_pre_check_msg_1="Fail: Don't find"
dia_pre_check_title_2="[/etc/host Update]"
dia_pre_check_yesno_1="First execut nutchez management interface."
dia_pre_check_yesno_2="Plz update /etc/hosts !!!"
pre_check_echo_1="Plz input root password to update /etc/hosts !!!"
pre_check_echo_2="Root password is error ! Plz check root password !!!"
dia_pre_check_yesno_3="nutch_nodes already be modified."

## [Lang for main_menu()] ##
dia_main_title_1="[Management Options]"
dia_main_menu_1_1="Check cluster status"
dia_main_menu_1_2="Setup datanode & tasktracker"
dia_main_menu_1_3="Setup namenode & jobtracker"
dia_main_menu_1_4="Start/Stop/Restart Tomcat"
dia_main_menu_1_5="Change Tomcat port"
dia_main_menu_1_6="Change language"

## [Lang for cluster_status()] ##
cluster_status_echo_1="[IP] \t\t [Hostname] \t [Network] \t [Dtatnode & Tasktracker]"
cluster_status_echo_2="Start to check cluster.."
cluster_status_read_1="Plz input anykey to continue.."
dia_cluster_status_title_1="[Cluster Status]"

## [Lang for srver_setup()] ##
dia_server_title_1="[Server Status]"
dia_server_msg_1="Namenode & Jobtracker are not running"
dia_server_msg_2="Jobtracker is running, Namenode is not running"
dia_server_msg_3="Namenode is running, Jobtracker is not running"
dia_server_msg_4="Namenode & Jobtracker are running"
dia_server_title_2="[Namenode & Jobtracker Setup]"
dia_server_menu_1_1="Start Namenode & Jobtracker"
dia_server_menu_1_2="Stop Namenode & Jobtracker"
dia_server_menu_1_3="Restart Namenode & Jobtracker"

## [Labg for cluster_setup()] ##
dia_cluster_setup_title_1="[All or Part nodes]"
dia_cluster_setup_menu_1_1="All nodes"
dia_cluster_setup_menu_1_2="Part nodes"
dia_cluster_setup_title_2="[Datanode & Tasktracker Nodes Choice]"
dia_cluster_setup_check_1="Choose Datanode & Tasktracker: "
dia_cluster_setup_title_3="[Datanode & Tasktracker Setup]"
dia_cluster_setup_menu_2_1="Start Datanodes & Tasktrackers"
dia_cluster_setup_menu_2_2="Stop Datanodes & Tasktrackers"
dia_cluster_setup_menu_2_3="Restart Datanodes & Tasktrackers"
cluster_setup_echo_1="[Start datanode & tasktracker]"
cluster_setup_echo_error="Can't ssh to "
cluster_setup_echo_3="[Stop datanode & tasktracker]"
cluster_setup_echo_5="[Restart datanode & tasktracker]"

## [Lang for tomcat_swith()] #
dia_tomcat_switch_title_1="[Tomcat Status]"
dia_tomcat_switch_msg_1="Tomcat is runing !!!"
dia_tomcat_switch_msg_2="Tomcat is not running !!!"
dia_tomcat_switch_title_2="[Tomcat Service Options]"
dia_tomcat_switch_menu_1_1="Start Tomcat"
dia_tomcat_switch_menu_1_2="Stop Tomcat"
dia_tomcat_switch_menu_1_3="Restart Tomcat"
tomcat_switch_echo_1="Faul: Don't fine"
tomcat_switch_echo_3="[Start Tomcat]"
tomcat_switch_echo_4="[Stop Tomcat]"
tomcat_switch_echo_5="[Restart Tomcat]"

## [Lang for tomcat_port()] ##
dia_tomcat_port_title_1="[Check Tomcat servel.xml]"
dia_tomcat_port_msg_1="Faill: Don't find"
dia_tomcat_port_title_2="[Tomcat Port Change]"
dia_tomcat_port_input_1="Plz input port number for tomcat (default is 8080)"

## [Lang for lang_switch()] ##
dia_lang_title_1="[Language Switch]"
dia_lang_menu_1_1="English"
dia_lang_menu_1_2="Chinese"

