#!/bin/bash
# Program:
#   Add crawl_nodes to /etc/hosts (for crawlzilla management interface).
#   $1=/home/crawler/crawlizlla/system/crawl_nodes
#   $2=/etc/hosts
# Author: 
#   Waue, Shunfa, Rock {waue, shunfa, rock}@nchc.org.tw
# Version:
#    1.0
# History:
#   2010/06/07  Rock    First release (1.0)

IPs=$(cat $1 | awk '{print $1}')
HOSTNAMEs=$(cat $1 | awk '{print $2}')
Crawlzilla_HOME="/home/crawler/crawlzilla"
# 刪除相同的 ip 在 /etc/hosts 和 crawl_nodes
for ip_addr in $(echo $IPs)
do
    jude=0
    cat $2 | grep ${ip_addr} || jude=1

    if [ $jude == 0 ]; then
        del_line=$(cat -n $2 | grep ${ip_addr} | awk '{print $1}')
        sed -i "${del_line}d" $2
    fi
done

# 刪除相同的 hostname 在 /etc/hosts 和 crawl_nodes
for host_name in $(echo $HOSTNAMEs)
do
    jude=0
    cat $2 | grep ${host_name} || jude=1

    if [ $jude == 0 ]; then
        del_line=$(cat -n $2 | grep ${host_name} | awk '{print $1}')
        sed -i "${del_line}d" $2
    fi
done

# Backup /etc/hosts
#cp -f "$2" "$2.bak"

# attache Crawl_nodes to hosts
sed -i '/# Crawlzilla add/d' $2
sed -i '/# Crawlzilla End/d' $2
#echo "# Crawlzilla add" >>$2
#cat $1 | grep -v '#' >>$2
echo "# Crawlzilla add" >${Crawlzilla_HOME}/system/hosts.tmp
cat $1 | grep -v '#' >>${Crawlzilla_HOME}/system/hosts.tmp
echo "# Crawlzilla End" >>${Crawlzilla_HOME}/system/hosts.tmp
cat $2 >> ${Crawlzilla_HOME}/system/hosts.tmp
cp ${Crawlzilla_HOME}/system/hosts.tmp /etc/hosts
rm ${Crawlzilla_HOME}/system/hosts.tmp

