#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Program:
#   remove shell script for client uninstall
# Author:
#   Waue, Shunfa, Rock {waue, shunfa, rock}@nchc.org.tw
# Version:
#    1.0
# History:
#    


# 需要 master_install 設定的參數區
# Master IP here
Master_IP_Address=your.master.ip.here
# Master Hostname here
Master_Hostname=input_your_master_hostname
crawlzilla_PATH=/home/crawler/crawlzilla/system


[ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"

##########  echo function  ##########
function debug_info () {
  if [ $? -eq 0 ]; then
    echo -e "\033[1;35;40m info - $1 \033[0m"
  fi
}


function show_info () {
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32;40m $1 \033[0m"
  fi
}
##########end echo function ##########

function load_default_lang(){

lang=$(locale | grep 'LANG=' | cut -d "=" -f2)

# Default: source english
. $crawlzilla_PATH/lang/lang_en_US
# if locale is zh then source chinese

echo $lang | grep 'zh' >> /dev/null && source $crawlzilla_PATH/lang/lang_zh_TW
}



# check root
function check_root(){
  debug_info "check_root"
  if [ $USER != "root" ]; then
    show_info "$CR_check_root_1" # "請切換成 root 身份執行移除程式!!!"
    exit
  fi
  show_info "$CR_check_root_2" # "已確認為root身份, 將繼續執行此移除程式！"
}

# shutdown service
function shutdown_service () {
  show_info "$CR_shutdown_service_echo_1" # "關閉本機服務..."
  su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop datanode"
  su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop tasktracker"
  show_info "$CR_shutdown_service_echo_2" # "本機服務已關閉"
}

# 移除檔案及資料夾
function remove_folders () {
  show_info "$CR_remove_folders_echo_1" # "正在刪除安裝時所建立的檔案及資料夾..."
  rm /usr/bin/crawlzilla_remove
  rm -rf /opt/crawlzilla
  rm -rf /var/lib/crawlzilla
  rm -rf /var/log/crawlzilla/
 
  # 刪除/tmp下的crawler檔案
  fileList=$(ls -al /tmp | grep crawler | awk '{print $8}')
    for file in $(echo $fileList)
      do
        rm -rf /tmp/$file
    done
  
  show_info "$CR_remove_folders_echo_2" # "安裝時所建立的檔案及資料夾已刪除"
}


# 還原/etc/hosts
function edit_hosts () {
  show_info "$CR_edit_hosts_echo_1" # "修改/etc/hosts..."
  if [ -e /home/crawler/crawlzilla/system/hosts.bak ];then 
    rm /etc/hosts 
    cp /home/crawler/crawlzilla/system/hosts.bak /etc/hosts
    show_info "$CR_edit_hosts_echo_2" # "完成修改/etc/hosts"
  elif [ -e /home/crawler/crawlzilla/system/hosts ];then
    rm /etc/hosts
    cp /home/crawler/crawlzilla/system/hosts /etc/hosts
    show_info "still using the /etc/hosts created by crawlzilla "
  elif [ -f /etc/hosts ];then
    show_info "/etc/hosts without recovered!!!"
  else
    show_info " bug ! /etc/hosts error !!!"
  fi
}

function edit_remove_list(){
# 透過scp master上的檔案判斷是否有網路or master是否有開啟
  scp -o StrictHostKeyChecking=no /etc/hosts crawler@$Master_IP_Address:/home/crawler/crawlzilla/system/go.sh /home/crawler/crawlzilla/system/ 
  if [ -e "/home/crawler/crawlzilla/system/go.sh" ] ;then
    Client_Hostname=$(hostname)
    IP_Address=$(cat /etc/hosts | grep $Client_Hostname | awk '{print $1}')
    su crawler -c "ssh -o StrictHostKeyChecking=no $Master_IP_Address echo $IP_Address \>\> ~/crawlzilla/system/remove_list"
    remove_flag=0
  elif [ ! -e "/home/crawler/crawlzilla/system/go.sh" ] ;then
    remove_flag=1
  fi
}


# 移除使用者
function user_delete () {
  show_info "$CR_user_delete_echo_1" # "正在刪除crawler使用者..."
  userdel -rf crawler >/dev/null 2>&1
  groupdel crawler >/dev/null 2>&1
  show_info "$CR_user_delete_echo_2" # "使用者crawler已刪除"
}

# Main function
function main () {
  load_default_lang
  check_root
  show_info "$CR_main_echo_1" #"警告 - 此一程式為移除此用戶端的crawl node, 若您為誤執行此一程式, 請按Ctrl+c離開此程序！"
  show_info "$CR_main_echo_2" #"本執行程序將會移除安裝crawlzilla時所新增的檔案及crawler使用者帳號"
# 詢問是否繼續
  read -p "$CR_main_echo_3" confirm # "請問是否確定移除此一節點：1.確定 2.取消"
# 確認移除
  if [ $confirm -eq 1 ]; then
    shutdown_service
    remove_folders
    edit_remove_list
    edit_hosts
    user_delete
    show_info "$CR_main_echo_4" # "移除程序已完成！"
  elif [ $confirm -eq 2 ]; then
    show_info "$CR_main_echo_5" # "您已取消移除程序！"
    show_info "$CR_main_echo_6" # "若要移除請再重新執行！"
  fi
  
  if [ $remove_flag -eq 1 ]; then
    show_info "You need to edit /home/crawler/crawlzilla/system/crawl_nodes and hosts at host $Master_IP_Address due to you lost connect."
  fi
}

if [ -e "/home/crawler/crawlzilla" ]; then
  main
else
  show_info "Installation is not complete!"
  show_info "Remove forcibly[1=agree/2=exit]"
  read -p "[1/2]: " force_do_remove
  if [ $force_do_remove -eq 1 ];then
    main
  else
    exit
  fi
fi
