#!/bin/bash
# Program:
#   remove shell script for master uninstall
# Author:
#   Waue, Shunfa, Rock {waue, shunfa, rock}@nchc.org.tw
# Version:
#    1.0
# History:
#   
[ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"

Work_Path=`dirname "$0"`

##########  echo function  ##########
function debug_info () {
  if [ $? -eq 0 ]; then
    echo -e "\033[1;35;40m info - $1 \033[0m"
  fi
}


function show_info () {
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32;40m $1 \033[0m"
  fi
}
##########end echo function ##########

crawlzilla_PATH=/home/crawler/crawlzilla/system


function load_default_lang(){

lang=$(locale | grep 'LANG=' | cut -d "=" -f2)

# Default: source english
. $crawlzilla_PATH/lang/lang_en_US
# if locale is zh then source chinese

echo $lang | grep 'zh' >> /dev/null && source $crawlzilla_PATH/lang/lang_zh_TW

}

# check root
function check_root(){
  debug_info "check_root"
  if [ $USER != "root" ]; then
    show_info "$MR_check_root_1" # "請切換成 root 身份執行移除程式!!!"
    exit
  fi
  show_info "$MR_check_root_2" # "已確認為root身份, 將繼續執行此移除程式！"
}

# shutdown service
function shutdown_service () {
  show_info "$MR_shutdown_service_echo_1" # "停止其他尚未關閉的slaves服務..."
  slaves_list=`cat /home/crawler/crawlzilla/system/crawl_nodes | cut -d' ' -f1`
  for i in $slaves_list ;
  do
      show_info "$i $MR_shutdown_service_echo_2" # "關閉本機服務..."
      su crawler -c 'ssh -o StrictHostKeyChecking=no $i /opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop tasktracker'
      su crawler -c 'ssh -o StrictHostKeyChecking=no $i /opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop datanode'
  done  

  show_info "$i $MR_shutdown_service_echo_2" # "關閉本機服務..."
  su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop jobtracker"
  su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop namenode"



  tom_pids=$(ps x | grep -v 'grep' | grep "tomcat" | awk '{print $1}')  
  if [ -n "$tom_pids" ]; then
    su crawler -c "/opt/crawlzilla/tomcat/bin/shutdown.sh"
  fi
  show_info "$MR_shutdown_service_echo_3" # "本機服務已關閉"
}

# 移除檔案及資料夾
function remove_folders () {
  rm /usr/bin/crawlzilla
  rm /usr/bin/crawlzilla_remove
  show_info "$MR_remove_folders_echo_1" # "正在刪除安裝時所建立的檔案及資料夾..."
  rm -rf /opt/crawlzilla
  rm -rf /var/log/crawlzilla
  rm -rf /var/lib/crawlzilla
  rm -rf /tmp/*.pid
  show_info "$MR_remove_folders_echo_2" # "安裝時所建立的檔案及資料夾已刪除"
}

# 還原/etc/hosts
function edit_hosts () {
  show_info "$CR_edit_hosts_echo_1" # "修改/etc/hosts..."
  if [ -e /home/crawler/crawlzilla/system/hosts.bak ];then
    rm /etc/hosts
    cp /home/crawler/crawlzilla/system/hosts.bak /etc/hosts
    show_info "$CR_edit_hosts_echo_2" # "完成修改/etc/hosts"
  elif [ -e /home/crawler/crawlzilla/system/hosts ];then
    rm /etc/hosts
    cp /home/crawler/crawlzilla/system/hosts /etc/hosts
    show_info "still using the /etc/hosts created by crawlzilla. "
  elif [ -f /etc/hosts ];then
    show_info "/etc/hosts without recovered!!!"
  else
    show_info " bug ! /etc/hosts error !!!"
  fi
}

# 移除使用者
function user_delete () {
  show_info "$MR_user_delete_echo_1" # "正在刪除crawler使用者..."
  userdel -rf crawler >/dev/null 2>&1
  groupdel crawler >/dev/null 2>&1
  show_info "$MR_user_delete_echo_2" # "使用者crawler已刪除"
}

# Main function
function main () {
  load_default_lang
  check_root
  show_info "$MR_main_echo_1" #"警告 - 此一程式為移除Crawlzilla程式, 若您為誤執行此一程式, 請按Ctrl+c離開此程序！"
  show_info "$MR_main_echo_2" #"本執行程序將會移除安裝Crawlzilla時所新增的檔案及crawler使用者帳號"
# 詢問是否繼續
  read -p "$MR_main_echo_3" confirm # "請問是否確定移除此一節點：1.確定 2.取消"
# 確認移除
  if [ $confirm -eq 1 ]; then
    shutdown_service
    remove_folders
    edit_hosts
    user_delete
    show_info "$MR_main_echo_4" # "移除程序已完成！"
  elif [ $confirm -eq 2 ]; then
    show_info "$MR_main_echo_5" # "您已取消移除程序！"
    show_info "$MR_main_echo_6" # "若要移除請再重新執行！"
  fi
}

if [ -e "/home/crawler/crawlzilla" ]; then
  main
else
  show_info "Installation is not complete!"
  show_info "Remove forcibly[1=agree/2=exit]"
  read -p "[1/2]: " force_do_remove
  if [ $force_do_remove -eq 1 ];then
    main
  else 
    exit
  fi
fi
