#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Program:
#   remove shell script for master uninstall
# Author:
#   Waue, Shunfa, Rock {waue, shunfa, rock}@nchc.org.tw
# Version:
#    1.0
# History:
#   

# [ Env para ] #
Crawlzilla_HOME="/home/crawler/crawlzilla"
Manu_Tmp_Path="/home/crawler/crawlzilla/.menu_tmp"
Hadoop_Daemon="/opt/crawlzilla/nutch/bin/hadoop-daemon.sh"
PID_Dir="/var/log/crawlzilla/hadoop-pids"


# [ System Load] #
## check user
#[ "`id -u`" != "0" ] && echo "please enter password of $USER:"  && exec sudo su -c "$0" "$@"
## language load 
source $Manu_Tmp_Path/lang

#  [ Function Description ] #

function error_info ( )
{ 
    echo -e "\033[1;35;40m ERROR: $1 \033[0m" 
}
function show_info ( ) 
{
    echo -e "\033[1;32;40m $1 \033[0m"
}

# check root
function check_root ( )
{
  [ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"
  if [ $USER != "root" ]; then
    show_info "$MR_check_root_1" # "請切換成 root 身份執行移除程式!!!"
    exit
  fi
  show_info "$MR_check_root_2" # "已確認為root身份, 將繼續執行此移除程式！"
}


#function for fast_shutdown_all computing nodes and tomcat server
function fast_shutdown_all ( )
{
  # shutdown tomcat
    show_info "$tomcat_switch_echo_4"
    tom_pids=$(ps ax | grep -v 'grep' | grep "tomcat" | awk '{print $1}')
    for tom_pid in $tom_pids
    do
        kill -9 $tom_pid 2>/dev/null
    done
  # kill hadoop
  if [ -e $PID_Dir/hadoop-crawler-datanode.pid ] || \
   [ -e $PID_Dir/hadoop-crawler-tasktracker.pid ] || \
   [ -e $PID_Dir/hadoop-crawler-namenodenode.pid ] || \
   [ -e $PID_Dir/hadoop-crawler-jobtracke.pid ];then
    kill -9 $(cat $PID_Dir/hadoop-crawler-datanode.pid) > /dev/null 2>&1 
    if [ ! $? -eq 0 ];then echo "datanode error !";fi
    kill -9 $(cat $PID_Dir/hadoop-crawler-tasktracker.pid) > /dev/null 2>&1
    if [ ! $? -eq 0 ];then echo "tasktracker error !";fi
    kill -9 $(cat $PID_Dir/hadoop-crawler-namenode.pid) > /dev/null 2>&1
    if [ ! $? -eq 0 ];then echo "namenode error !";fi
    kill -9 $(cat $PID_Dir/hadoop-crawler-jobtracker.pid) > /dev/null 2>&1
    if [ ! $? -eq 0 ];then echo "jobtracker error !";fi
  else 
   echo "ERROR ! cannot find $PID_Dir/*pid file"
   exit 8
  fi
}

# 移除檔案及資料夾
function remove_folders () {
  show_info "$MR_remove_folders_echo_1" # "正在刪除安裝時所建立的檔案及資料夾..."
  rm /usr/bin/crawlzilla
  rm /usr/bin/crawlzilla_remove
  rm -rf /opt/crawlzilla
  rm -rf /var/log/crawlzilla
  rm -rf /var/lib/crawlzilla
  
  show_info "$MR_remove_folders_echo_2" # "安裝時所建立的檔案及資料夾已刪除"
}

# recover /etc/hosts
function recover_hosts () {
  show_info "$CR_edit_hosts_echo_1" # "修改/etc/hosts..."
  if [ -e /home/crawler/crawlzilla/system/hosts.bak ];then
    rm /etc/hosts
    cp /home/crawler/crawlzilla/system/hosts.bak /etc/hosts
    show_info "$CR_edit_hosts_echo_2" # "完成修改/etc/hosts"
  elif [ -e /home/crawler/crawlzilla/system/hosts ];then
    rm /etc/hosts
    cp /home/crawler/crawlzilla/system/hosts /etc/hosts
    show_info "still using the /etc/hosts created by crawlzilla. "
  elif [ -f /etc/hosts ];then
    show_info " WARNNING ! Please check your /etc/hosts correct or not!"
  else
    show_info " BUG ! /etc/hosts error !!!"
  fi
}

# remove user
function user_delete () {
  show_info "$MR_user_delete_echo_1" # "正在刪除crawler使用者..."
  userdel -rf crawler >/dev/null 2>&1
  groupdel crawler >/dev/null 2>&1
  show_info "$MR_user_delete_echo_2" # "使用者crawler已刪除"
}

# Main function
function main () {
  show_info "$MR_main_echo_1" # a warnning hint
  show_info "$MR_main_echo_2" # a remove hint 
  # confirm 
  LOCK=0
  while [ "$LOCK" == "0" ];
  do
    read -p "$MR_main_echo_3" confirm # confirm 1.確定 2.取消"
  # make sure
    if [ $confirm -eq 1 ]; then
      fast_shutdown_all
      show_info "shutdown service"
      remove_folders
      show_info "remove_folders"
      recover_hosts
      show_info "recover hosts"
      user_delete
      show_info "user_delete"
      show_info "$MR_main_echo_4" # "移除程序已完成！"
      LOCK=1; 
    elif [ $confirm -eq 2 ]; then
      show_info "$MR_main_echo_5" # "您已取消移除程序！"
      show_info "$MR_main_echo_6" # "若要移除請再重新執行！"
      LOCK=1; 
    else
      show_info "Hint: 1 => yes, 2 => exit "
      show_info "Please enter 1 or 2"
    fi
  done
}

# [ Process Go ]

check_root
if [ ! -e "/home/crawler/crawlzilla" ] || [ ! -e "/opt/crawlzilla" ] ; then
  show_info "Installation is not complete!"
  show_info "Remove forcibly[1=agree/2=exit]"
  read -p "[1/2]: " force_do_remove
  if [ ! "$force_do_remove" == "1" ];then
    exit 0;
  fi
fi
main
