#!/bin/bash
# Program:
#   Chinese Language file for client_remove
# Author:
#   Waue, Shunfa, Rock {waue, shunfa, rock}@nchc.org.tw
# Version:
#    1.0
# History:
#  

# check root
check_root_1="請切換成 root 身份執行移除程式!!!"
check_root_2="已確認為root身份, 將繼續執行此移除程式！"

# shutdown service
shutdown_service_echo_1="停止其他尚未關閉的slaves服務..."
shutdown_service_echo_2="關閉本機服務..."
shutdown_service_echo_3="本機服務已關閉"

# remove_folders
remove_folders_echo_1="正在刪除安裝時所建立的檔案及資料夾..."
remove_folders_echo_2="安裝時所建立的檔案及資料夾已刪除"

# edit_hosts
edit_hosts_echo_1="修改/etc/hosts..."
edit_hosts_echo_2="完成修改/etc/hosts"

# user_delete
user_delete_echo_1="正在刪除nutchuser使用者..."
user_delete_echo_2="使用者nutchuser已刪除"

# main
main_echo_1="警告 - 此一程式為移除nutchEZ程式, 若您為誤執行此一程式, 請按Ctrl+c離開此程序！"
main_echo_2="本執行程序將會移除安裝nutchEZ時所新增的檔案及nutchuser使用者帳號。"
main_echo_3="請問是否確定移除此一節點：1.確定 2.取消"
main_echo_4="移除程序已完成！"
main_echo_5="您已取消移除程序！"
main_echo_6="若要移除請再重新執行！"

